- name: Deploy the war file into JBoss
  hosts: all
  remote_user: ubuntu
  become: yes

  tasks:
      
    - name: Download JAR from Artifact
      environment:
        GITHUB_TOKEN: "{{ secrets.Workflow2_PAT_TOKEN_GITHUB }}"
      shell: |
        PACKAGE_NAME="java-ant-sonar"
        VERSION="1.0.2"
        curl -LO "https://maven.pkg.github.com/lf-common-repo/shared-workflow/$PACKAGE_NAME/$VERSION/java-ant-sonar-$VERSION.jar"

    - name: Move JAR file to /home/ubuntu/app-dir/
      ansible.builtin.shell: >
        mv "java-ant-sonar-1.0.2.jar" /home/ubuntu/app-dir/helloworld.jar && chmod 755 /home/ubuntu/app-dir/helloworld.jar
      args:
        executable: /bin/bash

    - name: List files in /opt/wildfly/bin/
      ansible.builtin.shell: ls -l /opt/wildfly/bin/

    - name: Echo WAR_PATH
      ansible.builtin.shell: echo "WAR_PATH: $WAR_PATH"
