name: caller-java-sonar-ci

on:
 workflow_dispatch:
  
jobs:
  caller-java-sonar-ci:
    uses: lf-common-repo/shared-workflow/.github/workflows/java-maven-sonar-ci.yml@main
    
    secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
         #configuration-path: ${{ inputs.config-path }}
         #SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         #SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
   
