name: app CI

on:
 workflow_dispatch:
 
 
jobs:

    trigger_javaci: 
      
       uses: lf-common-repo/shared-workflow/.github/workflows/java-maven-ci.yml@main
      
       secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
