name: extract release file

on:
 workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - run:
        chmod +x deploy.sh

    - name: Deploy 
      run: |
        ./deploy.sh
        git config user.email "actions@github.com"
        git config user.name "GitHub Actions"
