name: Publish to GitHub Packages
on:
  workflow_dispatch:

jobs:
  publish:
    name: Publish JARs to GitHub Packages
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download JAR files
        run: |
          mkdir jars
          wget -P jars https://github.com/lf-retail/app-service/helloworld.jar

      - name: Build and Publish
        run: |
          PACKAGE_PATH=com/lf-retail/app-service
          VERSION=1.0.0

          for jar_file in $(ls jars/*.jar); do
            artifact_id=$(basename $jar_file .jar)
            mvn deploy:deploy-file \
              -Dfile=$jar_file \
              -DgroupId=$PACKAGE_PATH \
              -DartifactId=$artifact_id \
              -Dversion=$VERSION \
              -Dpackaging=jar \
              -DrepositoryId=github \
              -Durl=https://maven.pkg.github.com/lf-retail/app-service
          done
        env:
          GITHUB_TOKEN: ${{ secrets.WORKFLOW2_PAT_TOKEN_GITHUB }}
