name: extract release file

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Make deploy.sh executable
      run: chmod +x deploy.sh

    - name: Deploy 
      id: deploy_step
      run: |
        dos2unix deploy.sh
        sudo -E ./deploy.sh

    - name: Make rollback.sh executable
      run: chmod +x rollback.sh

    - name: Rollback on Failure
      if: failure()
      run: |
        # Call rollback.sh script here
        ./rollback.sh rollback.txt
