name: extract release file

on:
 workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Make deploy.sh executable      
      run: |
        chmod +x deploy.sh

    - name: Deploy 
      run: |
        ./deploy.sh
