name: jboss-caller-new

on:
 workflow_dispatch:
 
env: 
  Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
  
jobs:
  caller-jboss-deploy:
     runs-on: ubuntu-latest
     steps:
      - name: Trigger Caller Workflowii
        uses: actions/checkout@v3
     
      - name: Run Callee Workflow
        run: |
          curl -X POST \
          -H "Accept: application/vnd.github.v3+json" \
          -H "Authorization: Bearer ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}" \
          
          https://api.github.com/repos/lf-common-repo/shared-workflow/actions/workflows/Jboss.yml/dispatches \
          -d '{"ref":"main"}'
