name: jboss-caller-new

on:
 workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}  
  
jobs:
  caller-jboss-deploy:
    runs-on: ubuntu-latest
    steps: 
      - name: deploy jboss   
        uses: lf-common-repo/shared-workflow/.github/workflows/Jboss.yml@main
        env:
           Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
