name: caller-java-sonar-ci

on:
 workflow_dispatch:
  
jobs:
  caller-java-sonar-ci:
    uses: lf-common-repo/shared-workflow/.github/workflows/jboss.yml@main
    
    secrets:
         Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
