name: jboss-caller-new

on:
 workflow_dispatch:
 
jobs:
  caller-jboss-deploy:
      #runs-on: ubuntu-latest
      #steps:
        #- name: jboss-deploy
          uses: lf-common-repo/shared-workflow/.github/workflows/Jboss.yml@main
          #with:
           #  config-path: .github/labeler.yml
          secrets:
            token: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}  
   
