name: jboss-caller-new

on:
 workflow_dispatch:
 
env: 
  Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
  
jobs:
  caller-jboss-deploy:
     runs-on: self-hosted
     steps:
      - name: Set Runner Info
        run: echo "RUNNER=custom-runner" >> $GITHUB_ENV

      - name: Run Called Workflow
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install @octokit/rest.js

      - name: Trigger Called Workflow
        uses: actions/github-script@v5
        with:
          script: |
            const { Octokit } = require("@octokit/rest.js"); // Correct package name
            const octokit = new Octokit({
              auth: process.env.Workflow2_PAT_TOKEN_GITHUB, // Use the appropriate token here
            });

            const response = await octokit.actions.createWorkflowDispatch({
              owner: 'lf-common-repo',
              repo: 'shared-workflow',
              workflow_id: 'Jboss.yml',
              ref: 'main',
              inputs: {
                runner: process.env.RUNNER
              }
            });
            console.log(response);    
        env:
           Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}             
