- name: Deploy the war file into JBoss
  hosts: all
  remote_user: ubuntu
  become: yes

  tasks:

    - name: Stop the application
      ansible.builtin.shell: >
        /opt/wildfly/bin/jboss-cli.sh --connect --controller=13.200.96.209 --user=jbadmin --password=jbadmin@123 --command="undeploy --name=helloworld.war"
      ignore_errors: yes

    - name: Backup Application
      ansible.builtin.archive:
        path: /home/ubuntu/app-dir/helloworld.war
        dest: /home/ubuntu/app-dir/backup/helloworld_backup_{{ ansible_date_time.date }}.tar.gz
      
      
    - name: Download JAR from Artifact
      environment:
        GITHUB_TOKEN: "{{ secrets.Workflow2_PAT_TOKEN_GITHUB }}"
      shell: |
        PACKAGE_NAME="java-ant-sonar"
        VERSION="1.0.2"
        curl -LO "https://maven.pkg.github.com/lf-common-repo/shared-workflow/$PACKAGE_NAME/$VERSION/java-ant-sonar-$VERSION.jar"

    - name: Move JAR file to /home/ubuntu/app-dir/
      ansible.builtin.shell: >
        mv "java-ant-sonar-1.0.2.jar" /home/ubuntu/app-dir/helloworld.jar && chmod 755 /home/ubuntu/app-dir/helloworld.jar
      args:
        executable: /bin/bash

    - name: List files in /opt/wildfly/bin/
      ansible.builtin.shell: ls -l /opt/wildfly/bin/

    - name: Echo WAR_PATH
      ansible.builtin.shell: echo "WAR_PATH: $WAR_PATH"

    #- name: Login to JBoss and deploy war file
     # environment:
      #  JBOSS_USERNAME: "{{ secrets.JBOSS_USERNAME }}"
       # JBOSS_PASSWORD: "{{ secrets.JBOSS_PASSWORD }}"      



    - name: Deploy application
      ansible.builtin.shell: >
        /opt/wildfly/bin/jboss-cli.sh --connect --controller=13.200.96.209 --user=jbadmin --password=jbadmin@123 --command="deploy /home/ubuntu/app-dir/helloworld.war"

    - name: Check deployment status
      ansible.builtin.shell: >
        /opt/wildfly/bin/jboss-cli.sh --connect --controller=13.200.96.209 --user=jbadmin --password=jbadmin@123  --command="deployment-info --name=helloworld.war"
