name: jboss-caller-new

on:
 workflow_dispatch:
 
jobs:
  caller-jboss-deploy:
      runs-on: self-hosted
      steps:
        - name: jboss-deploy
          uses: lf-common-repo/shared-workflow/.github/workflows/Jboss.yml@main
          with:
             runner: "[\"self-hosted\"]"
             #Workflow2_PAT_TOKEN_GITHUB: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
   
