name: Deploy WAR to JBoss

on:
  workflow_dispatch:
env:
  GITHUB_TOKEN: ${{ secrets.Workflow2_PAT_TOKEN_GITHUB }}
  
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: list 
        run: |
         ls -l /opt/wildfly/bin/
         echo "WAR_PATH: $WAR_PATH"
         


      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'  
          
      - name: login to JBoss and deploy war file
        env:
          JBOSS_USERNAME: ${{ secrets.JBOSS_USERNAME }} 
          JBOSS_PASSWORD: ${{ secrets.JBOSS_PASSWORD }} 
          
        run: |
        
         echo "Running undeploy command"
         /opt/wildfly/bin/jboss-cli.sh --connect --controller=13.234.120.105 --user=$JBOSS_USERNAME --password=$JBOSS_PASSWORD  --command="undeploy --name=helloworld.war"
         
         echo "Running deploy command"
         /opt/wildfly/bin/jboss-cli.sh --connect --controller=13.234.120.105 --user=$JBOSS_USERNAME --password=$JBOSS_PASSWORD  --command="deploy /home/ubuntu/app-dir/helloworld.war"
         
         echo "Running deploy status command"
         /opt/wildfly/bin/jboss-cli.sh --connect --controller=13.234.120.105 --user=$JBOSS_USERNAME --password=$JBOSS_PASSWORD  --command="deployment-info --name=helloworld.war"
         
